project:
  type: book
  output-dir: docs

book:
  title: "Mammalian Organogenesis"
  reader-mode: true
  page-footer:
    left: |
      Build by Jhuanglab
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://jhuanglab.github.io/embryo/
  repo-url: https://jhuanglab.github.io/embryo/
  repo-branch: main
  repo-actions: [issue]
  chapters:

    - href: index.qmd
      text: Preface

    - href: welcome.qmd
      text: Welcome
    - href: intro.qmd
      text: Introduction

    - part: Data Collection
      chapters:
        - href: datasets.qmd
          text: Data Sets


    - part: Data Preprocessing
      chapters:
        - href: qc.qmd
          text: Quality Control
        - href: clustering.qmd
          text: Clustering
    - part: Unsupervised cluster
      chapters:

        - href: reduce_dim.qmd
          text: Reduce Dim

    - part: Analysis
      chapters:

        - href: drug.qmd
          text: Treatment
        - href: mmyelomap.qmd
          text: The Mmyelomap

    - part: Visualization
      chapters:
        - href: fig1.qmd
          text: "Figure 1"
        - href: fig2.qmd
          text: "Figure 2"
        - href: fig3.qmd
          text: "Figure 3"

    - part: Communication
      chapters:
        - href: faq.qmd
          text: FAQ
        - href: contactus.qmd
          text: Contact us

    - part: Appendix
      chapters:
        - href: functions.qmd
          text: Functions
        - href: acknowledgement.qmd
          text: Acknowledgement
        - href: final.qmd
          text: Final Words

    - href: references.qmd
      text: References

format:
  html:
    bibliography: references.bib
    reference-location: document
    theme:
      - cosmo
      - mm.scss
    code-link: true
    code-exec-button: false
    author-meta: "Jinyan Huang"
    callout-appearance: simple
execute:
  eval: false
  echo: true
editor: source
