# Preface {.unnumbered}

---
title: "Spatiotemporal Metabolic Atlas of Mammalian Organogenesis" 
---

Organogenesis in mammals involves a highly orchestrated series of spatially and temporally regulated cellular processes. These processes are tightly coupled to transcriptional networks and metabolic pathways, but how these factors cooperately drive complex morphogenesis remains poorly understood. Here, we constructed spatiotemporal transcriptional networks and a comprehensive metabolic atlas to delineate the dynamic metabolic landscape during organogenesis. Integrated analysis revealed that each organ acquired specific metabolic features, with the liver and brain exhibiting particularly pronounced specifications. This organ-specific metabolism emerges progressively from an initially homogeneous metabolic pattern distributed across the entire embryo. Within the organs, we identified a series of spatially organized metabolic patterns, gradients or niches in the developing somite or brain, which were often aligned with signaling pathways or cell fate transitions. Comparative analysis of mouse and human embryo organ development demonstrated that mouse embryos, undergo more rapid organ-level metabolic specification than human embryos, consistent with their developmental pace. 

Collectively, these findings highlight the spatiotemporal heterogeneity of organ-level metabolism and underscore the fundamental roles of metabolic specification in mammalian organogenesis.
